server:
  port: 8080

secret:
  param1: YANDEX_API_KEY
  param2: YANDEX_FOLDER_ID

spring:
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: postgres
    password: ilia
  flyway:
    jdbc-properties:
      enabled: true
      locations:
        - db.migration

